apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobalt-dingo
  namespace: cobalt-dingo
  labels:
    app: cobalt-dingo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobalt-dingo
  template:
    metadata:
      labels:
        app: cobalt-dingo
    spec:
      containers:
        - name: cobalt-dingo
          image: cobalt-dingo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
