// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batches.sql

package pgstore

import (
	"context"
	"database/sql"
	"time"
)

const getBatch = `-- name: GetBatch :one
SELECT id, tenant_id, msg_id, status, xml, created_at, submitted_at
FROM payment_batches
WHERE tenant_id = $1 AND id = $2
`

type GetBatchParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetBatch(ctx context.Context, arg GetBatchParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, getBatch, arg.TenantID, arg.ID)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MsgID,
		&i.Status,
		&i.Xml,
		&i.CreatedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const getBatchItems = `-- name: GetBatchItems :many
SELECT id, batch_id, fortnox_invoice_number, supplier_name,
       supplier_iban, supplier_bic, currency, amount_minor_units,
       due_date, execution_rate
FROM batch_items
WHERE batch_id = $1
`

func (q *Queries) GetBatchItems(ctx context.Context, batchID string) ([]BatchItem, error) {
	rows, err := q.db.QueryContext(ctx, getBatchItems, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchItem
	for rows.Next() {
		var i BatchItem
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.FortnoxInvoiceNumber,
			&i.SupplierName,
			&i.SupplierIban,
			&i.SupplierBic,
			&i.Currency,
			&i.AmountMinorUnits,
			&i.DueDate,
			&i.ExecutionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBatch = `-- name: InsertBatch :one
INSERT INTO payment_batches (id, tenant_id, msg_id, status, xml)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, msg_id, status, xml, created_at, submitted_at
`

type InsertBatchParams struct {
	ID       string
	TenantID string
	MsgID    string
	Status   string
	Xml      []byte
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (PaymentBatch, error) {
	row := q.db.QueryRowContext(ctx, insertBatch,
		arg.ID,
		arg.TenantID,
		arg.MsgID,
		arg.Status,
		arg.Xml,
	)
	var i PaymentBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MsgID,
		&i.Status,
		&i.Xml,
		&i.CreatedAt,
		&i.SubmittedAt,
	)
	return i, err
}

const insertBatchItem = `-- name: InsertBatchItem :exec
INSERT INTO batch_items (
    id, batch_id, fortnox_invoice_number, supplier_name,
    supplier_iban, supplier_bic, currency, amount_minor_units, due_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertBatchItemParams struct {
	ID                   string
	BatchID              string
	FortnoxInvoiceNumber int32
	SupplierName         string
	SupplierIban         string
	SupplierBic          string
	Currency             string
	AmountMinorUnits     int64
	DueDate              time.Time
}

func (q *Queries) InsertBatchItem(ctx context.Context, arg InsertBatchItemParams) error {
	_, err := q.db.ExecContext(ctx, insertBatchItem,
		arg.ID,
		arg.BatchID,
		arg.FortnoxInvoiceNumber,
		arg.SupplierName,
		arg.SupplierIban,
		arg.SupplierBic,
		arg.Currency,
		arg.AmountMinorUnits,
		arg.DueDate,
	)
	return err
}

const listBatches = `-- name: ListBatches :many
SELECT id, tenant_id, msg_id, status, xml, created_at, submitted_at
FROM payment_batches
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBatches(ctx context.Context, tenantID string) ([]PaymentBatch, error) {
	rows, err := q.db.QueryContext(ctx, listBatches, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentBatch
	for rows.Next() {
		var i PaymentBatch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MsgID,
			&i.Status,
			&i.Xml,
			&i.CreatedAt,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExecutionRate = `-- name: SetExecutionRate :exec
UPDATE batch_items
SET execution_rate = $1
WHERE batch_id = $2 AND fortnox_invoice_number = $3
`

type SetExecutionRateParams struct {
	ExecutionRate        sql.NullString
	BatchID              string
	FortnoxInvoiceNumber int32
}

func (q *Queries) SetExecutionRate(ctx context.Context, arg SetExecutionRateParams) error {
	_, err := q.db.ExecContext(ctx, setExecutionRate, arg.ExecutionRate, arg.BatchID, arg.FortnoxInvoiceNumber)
	return err
}

const updateBatchStatus = `-- name: UpdateBatchStatus :exec
UPDATE payment_batches
SET status       = $2,
    submitted_at = CASE WHEN $2 = 'submitted' THEN NOW() ELSE submitted_at END
WHERE id = $1
`

type UpdateBatchStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateBatchStatus(ctx context.Context, arg UpdateBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBatchStatus, arg.ID, arg.Status)
	return err
}
