// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgstore

import (
	"database/sql"
	"time"
)

type BatchItem struct {
	ID                   string
	BatchID              string
	FortnoxInvoiceNumber int32
	SupplierName         string
	SupplierIban         string
	SupplierBic          string
	Currency             string
	AmountMinorUnits     int64
	DueDate              time.Time
	ExecutionRate        sql.NullString
}

type DebtorAccount struct {
	ID         string
	TenantID   string
	Name       string
	Iban       string
	Bic        string
	PispHandle sql.NullString
	IsDefault  bool
	CreatedAt  time.Time
}

type FortnoxToken struct {
	TenantID     string
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	UpdatedAt    time.Time
}

type PaymentBatch struct {
	ID          string
	TenantID    string
	MsgID       string
	Status      string
	Xml         []byte
	CreatedAt   time.Time
	SubmittedAt sql.NullTime
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt time.Time
}
