// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package pgstore

import (
	"context"
	"database/sql"
)

const getDefaultDebtorAccount = `-- name: GetDefaultDebtorAccount :one
SELECT id, tenant_id, name, iban, bic, pisp_handle, is_default, created_at
FROM debtor_accounts
WHERE tenant_id = $1 AND is_default = TRUE
`

func (q *Queries) GetDefaultDebtorAccount(ctx context.Context, tenantID string) (DebtorAccount, error) {
	row := q.db.QueryRowContext(ctx, getDefaultDebtorAccount, tenantID)
	var i DebtorAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Iban,
		&i.Bic,
		&i.PispHandle,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const upsertDebtorAccount = `-- name: UpsertDebtorAccount :exec
INSERT INTO debtor_accounts (id, tenant_id, name, iban, bic, pisp_handle, is_default)
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id) WHERE is_default = TRUE
DO UPDATE SET
    name        = EXCLUDED.name,
    iban        = EXCLUDED.iban,
    bic         = EXCLUDED.bic,
    pisp_handle = EXCLUDED.pisp_handle
`

type UpsertDebtorAccountParams struct {
	TenantID   string
	Name       string
	Iban       string
	Bic        string
	PispHandle sql.NullString
	IsDefault  bool
}

func (q *Queries) UpsertDebtorAccount(ctx context.Context, arg UpsertDebtorAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertDebtorAccount,
		arg.TenantID,
		arg.Name,
		arg.Iban,
		arg.Bic,
		arg.PispHandle,
		arg.IsDefault,
	)
	return err
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
`

type UpsertTenantParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenant, arg.ID, arg.Name)
	return err
}
