// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package pgstore

import (
	"context"
	"database/sql"
)

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM fortnox_integrations WHERE owner_id = $1 AND mode = $2
`

type DeleteIntegrationParams struct {
	OwnerID string
	Mode    string
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, deleteIntegration, arg.OwnerID, arg.Mode)
	return err
}

const getDefaultDebtorAccount = `-- name: GetDefaultDebtorAccount :one
SELECT id, tenant_id, name, iban, bic, pisp_handle, is_default, created_at
FROM debtor_accounts
WHERE tenant_id = $1 AND is_default = TRUE
`

func (q *Queries) GetDefaultDebtorAccount(ctx context.Context, tenantID string) (DebtorAccount, error) {
	row := q.db.QueryRowContext(ctx, getDefaultDebtorAccount, tenantID)
	var i DebtorAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Iban,
		&i.Bic,
		&i.PispHandle,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getIntegration = `-- name: GetIntegration :one
SELECT owner_id, mode, client_id, client_secret_sealed
FROM fortnox_integrations
WHERE owner_id = $1 AND mode = $2
`

type GetIntegrationParams struct {
	OwnerID string
	Mode    string
}

type GetIntegrationRow struct {
	OwnerID            string
	Mode               string
	ClientID           string
	ClientSecretSealed string
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (GetIntegrationRow, error) {
	row := q.db.QueryRowContext(ctx, getIntegration, arg.OwnerID, arg.Mode)
	var i GetIntegrationRow
	err := row.Scan(
		&i.OwnerID,
		&i.Mode,
		&i.ClientID,
		&i.ClientSecretSealed,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email) VALUES ($1, $2)
ON CONFLICT (email) DO NOTHING
`

type InsertUserParams struct {
	ID    string
	Email string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.ID, arg.Email)
	return err
}

const listTenantsByPrefix = `-- name: ListTenantsByPrefix :many
SELECT id, name, created_at
FROM tenants
WHERE id LIKE $1
ORDER BY name
`

// Tenant ids are "<sub>:<mode>:<company>", so a prefix of "<sub>:<mode>:"
// lists every company one user has connected in one mode. The prefix is
// matched literally: LIKE metacharacters in it are escaped by the caller.
func (q *Queries) ListTenantsByPrefix(ctx context.Context, id string) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsByPrefix, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserSubject = `-- name: RecordUserSubject :exec
INSERT INTO user_subjects (user_id, sub, issuer)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sub) DO UPDATE SET last_seen = NOW()
`

type RecordUserSubjectParams struct {
	UserID string
	Sub    string
	Issuer string
}

func (q *Queries) RecordUserSubject(ctx context.Context, arg RecordUserSubjectParams) error {
	_, err := q.db.ExecContext(ctx, recordUserSubject, arg.UserID, arg.Sub, arg.Issuer)
	return err
}

const upsertDebtorAccount = `-- name: UpsertDebtorAccount :exec
INSERT INTO debtor_accounts (id, tenant_id, name, iban, bic, pisp_handle, is_default)
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id) WHERE is_default = TRUE
DO UPDATE SET
    name        = EXCLUDED.name,
    iban        = EXCLUDED.iban,
    bic         = EXCLUDED.bic,
    pisp_handle = EXCLUDED.pisp_handle
`

type UpsertDebtorAccountParams struct {
	TenantID   string
	Name       string
	Iban       string
	Bic        string
	PispHandle sql.NullString
	IsDefault  bool
}

func (q *Queries) UpsertDebtorAccount(ctx context.Context, arg UpsertDebtorAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertDebtorAccount,
		arg.TenantID,
		arg.Name,
		arg.Iban,
		arg.Bic,
		arg.PispHandle,
		arg.IsDefault,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :exec
INSERT INTO fortnox_integrations (owner_id, mode, client_id, client_secret_sealed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, mode) DO UPDATE SET
    client_id            = EXCLUDED.client_id,
    client_secret_sealed = EXCLUDED.client_secret_sealed,
    updated_at           = NOW()
`

type UpsertIntegrationParams struct {
	OwnerID            string
	Mode               string
	ClientID           string
	ClientSecretSealed string
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertIntegration,
		arg.OwnerID,
		arg.Mode,
		arg.ClientID,
		arg.ClientSecretSealed,
	)
	return err
}

const upsertTenant = `-- name: UpsertTenant :exec
INSERT INTO tenants (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
`

type UpsertTenantParams struct {
	ID   string
	Name string
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenant, arg.ID, arg.Name)
	return err
}
