// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package pgstore

import (
	"context"
	"time"
)

const atomicRefreshToken = `-- name: AtomicRefreshToken :one
UPDATE fortnox_tokens
SET access_token  = $3,
    refresh_token = $4,
    expires_at    = $5,
    updated_at    = NOW()
WHERE tenant_id = $1 AND refresh_token = $2
RETURNING tenant_id
`

type AtomicRefreshTokenParams struct {
	TenantID       string
	RefreshToken   string
	AccessToken    string
	RefreshToken_2 string
	ExpiresAt      time.Time
}

// Replaces the token only when the stored refresh_token still matches old_refresh_token.
// Returns the tenant_id row when successful; zero rows means ErrTokenConflict.
func (q *Queries) AtomicRefreshToken(ctx context.Context, arg AtomicRefreshTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, atomicRefreshToken,
		arg.TenantID,
		arg.RefreshToken,
		arg.AccessToken,
		arg.RefreshToken_2,
		arg.ExpiresAt,
	)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getToken = `-- name: GetToken :one
SELECT access_token, refresh_token, expires_at
FROM fortnox_tokens
WHERE tenant_id = $1
`

type GetTokenRow struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
}

func (q *Queries) GetToken(ctx context.Context, tenantID string) (GetTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getToken, tenantID)
	var i GetTokenRow
	err := row.Scan(&i.AccessToken, &i.RefreshToken, &i.ExpiresAt)
	return i, err
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO fortnox_tokens (tenant_id, access_token, refresh_token, expires_at, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (tenant_id) DO UPDATE SET
    access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at    = EXCLUDED.expires_at,
    updated_at    = NOW()
`

type UpsertTokenParams struct {
	TenantID     string
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertToken,
		arg.TenantID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
