// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voucher_cache.sql

package pgstore

import (
	"context"
	"encoding/json"
	"time"
)

const deleteCachedYear = `-- name: DeleteCachedYear :exec
DELETE FROM fortnox_voucher_cache WHERE tenant_id = $1 AND year_id = $2
`

type DeleteCachedYearParams struct {
	TenantID string
	YearID   int32
}

// SaveYear replaces rather than merges: a merge cannot remove a voucher, so a
// bad write would be permanent.
func (q *Queries) DeleteCachedYear(ctx context.Context, arg DeleteCachedYearParams) error {
	_, err := q.db.ExecContext(ctx, deleteCachedYear, arg.TenantID, arg.YearID)
	return err
}

const getVoucherSync = `-- name: GetVoucherSync :one
SELECT synced_at, remote_total, fetch_version
FROM fortnox_voucher_sync
WHERE tenant_id = $1 AND year_id = $2
`

type GetVoucherSyncParams struct {
	TenantID string
	YearID   int32
}

type GetVoucherSyncRow struct {
	SyncedAt     time.Time
	RemoteTotal  int32
	FetchVersion int32
}

func (q *Queries) GetVoucherSync(ctx context.Context, arg GetVoucherSyncParams) (GetVoucherSyncRow, error) {
	row := q.db.QueryRowContext(ctx, getVoucherSync, arg.TenantID, arg.YearID)
	var i GetVoucherSyncRow
	err := row.Scan(&i.SyncedAt, &i.RemoteTotal, &i.FetchVersion)
	return i, err
}

const listCachedVouchers = `-- name: ListCachedVouchers :many
SELECT series, number, transaction_date, description, rows
FROM fortnox_voucher_cache
WHERE tenant_id = $1 AND year_id = $2
ORDER BY transaction_date, series, number
`

type ListCachedVouchersParams struct {
	TenantID string
	YearID   int32
}

type ListCachedVouchersRow struct {
	Series          string
	Number          int32
	TransactionDate time.Time
	Description     string
	Rows            json.RawMessage
}

// Ordered so a cached answer is byte-identical between reads; an unstable
// order makes two correct answers look like a discrepancy.
func (q *Queries) ListCachedVouchers(ctx context.Context, arg ListCachedVouchersParams) ([]ListCachedVouchersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCachedVouchers, arg.TenantID, arg.YearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCachedVouchersRow
	for rows.Next() {
		var i ListCachedVouchersRow
		if err := rows.Scan(
			&i.Series,
			&i.Number,
			&i.TransactionDate,
			&i.Description,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCachedVoucher = `-- name: UpsertCachedVoucher :exec
INSERT INTO fortnox_voucher_cache (
    tenant_id, year_id, series, number, transaction_date, description, rows
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, year_id, series, number) DO UPDATE
SET transaction_date = EXCLUDED.transaction_date,
    description      = EXCLUDED.description,
    rows             = EXCLUDED.rows
`

type UpsertCachedVoucherParams struct {
	TenantID        string
	YearID          int32
	Series          string
	Number          int32
	TransactionDate time.Time
	Description     string
	Rows            json.RawMessage
}

// Rows arrive as JSONB. Upsert rather than insert so a resync of an unchanged
// voucher is a no-op rather than a conflict.
func (q *Queries) UpsertCachedVoucher(ctx context.Context, arg UpsertCachedVoucherParams) error {
	_, err := q.db.ExecContext(ctx, upsertCachedVoucher,
		arg.TenantID,
		arg.YearID,
		arg.Series,
		arg.Number,
		arg.TransactionDate,
		arg.Description,
		arg.Rows,
	)
	return err
}

const upsertVoucherSync = `-- name: UpsertVoucherSync :exec
INSERT INTO fortnox_voucher_sync (tenant_id, year_id, synced_at, remote_total, fetch_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, year_id) DO UPDATE
SET synced_at     = EXCLUDED.synced_at,
    remote_total  = EXCLUDED.remote_total,
    fetch_version = EXCLUDED.fetch_version
`

type UpsertVoucherSyncParams struct {
	TenantID     string
	YearID       int32
	SyncedAt     time.Time
	RemoteTotal  int32
	FetchVersion int32
}

// fetch_version records which code produced the rows. Without it, a change to
// how rows are read leaves the count identical and every cached row wrong —
// see domain.VoucherFetchVersion.
func (q *Queries) UpsertVoucherSync(ctx context.Context, arg UpsertVoucherSyncParams) error {
	_, err := q.db.ExecContext(ctx, upsertVoucherSync,
		arg.TenantID,
		arg.YearID,
		arg.SyncedAt,
		arg.RemoteTotal,
		arg.FetchVersion,
	)
	return err
}
