// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — cobalt-dingo</title><link rel=\"stylesheet\" href=\"/static/css/green-chlorophyll.min.css\"><script src=\"https://unpkg.com/htmx.org@2.0.4\" integrity=\"sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+\" crossorigin=\"anonymous\"></script><style>\n\t\t\t\tbody {\n\t\t\t\t\tfont-family: \"SEB SansSerif\", sans-serif;\n\t\t\t\t\tbackground-color: var(--gds-sys-color-base-100);\n\t\t\t\t\tcolor: var(--gds-sys-color-text-primary);\n\t\t\t\t\tmin-height: 100vh;\n\t\t\t\t\tmargin: 0;\n\t\t\t\t}\n\t\t\t\t.cd-nav {\n\t\t\t\t\tbackground: var(--gds-sys-color-background-primary);\n\t\t\t\t\tborder-bottom: 1px solid var(--gds-sys-color-base-300);\n\t\t\t\t\tpadding: 1rem 1.5rem;\n\t\t\t\t\tdisplay: flex;\n\t\t\t\t\talign-items: center;\n\t\t\t\t\tgap: 0.75rem;\n\t\t\t\t}\n\t\t\t\t.cd-nav-brand {\n\t\t\t\t\tfont-weight: 500;\n\t\t\t\t\tfont-size: 1rem;\n\t\t\t\t\tcolor: var(--gds-sys-color-base-900);\n\t\t\t\t\tletter-spacing: -0.01em;\n\t\t\t\t}\n\t\t\t\t.cd-nav-divider {\n\t\t\t\t\tcolor: var(--gds-sys-color-base-400);\n\t\t\t\t}\n\t\t\t\t.cd-nav-sub {\n\t\t\t\t\tfont-size: 0.875rem;\n\t\t\t\t\tcolor: var(--gds-sys-color-text-secondary);\n\t\t\t\t}\n\t\t\t\t.cd-main {\n\t\t\t\t\tmax-width: 960px;\n\t\t\t\t\tmargin: 0 auto;\n\t\t\t\t\tpadding: 2rem 1.5rem;\n\t\t\t\t}\n\t\t\t</style></head><body><nav class=\"cd-nav\"><span class=\"cd-nav-brand\">cobalt-dingo</span> <span class=\"cd-nav-divider\">|</span> <a href=\"/invoices\" class=\"cd-nav-sub\" style=\"text-decoration:none;color:inherit;\">Invoices</a> <span class=\"cd-nav-divider\">·</span> <a href=\"/chat\" class=\"cd-nav-sub\" style=\"text-decoration:none;color:inherit;\">Chat</a></nav><main class=\"cd-main\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
